version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: decel_redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    container_name: decel_postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
